# Generated by Django 6.0.7 on 2026-07-20 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('borrowings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.CheckConstraint(condition=models.Q(('actual_return_date__gte', models.F('borrow_date'))), name='expected_return_date_gte_borrow_date_borrowing'),
        ),
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.CheckConstraint(condition=models.Q(('expected_return_date__gte', models.F('borrow_date'))), name='actual_return_date_gte_borrow_date_borrowing'),
        ),
    ]
